// File generated by FlutterFire CLI.
// You need to run `flutterfire configure` to generate proper configuration.
// This is a placeholder file - replace with actual Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To configure this file properly:
/// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
/// 2. Run: flutterfire configure
/// 3. Replace this file with the generated firebase_options.dart
///
/// Example:
///   await Firebase.initializeApp(
///     options: DefaultFirebaseOptions.currentPlatform,
///   );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Run `flutterfire configure` to generate proper values

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB8M0oJ9aphVcgoXduCuEtd2cPEOmq-vc',
    appId: '1:726428908817:web:1a20c7dbc3b6c1b555a0b0',
    messagingSenderId: '726428908817',
    projectId: 'my-coach-flutter',
    authDomain: 'my-coach-flutter.firebaseapp.com',
    storageBucket: 'my-coach-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIeV6MvXnk6NG8hWpaFEf2PaIR5AYoIk',
    appId: '1:726428908817:android:d08c7643710311d255a0b0',
    messagingSenderId: '726428908817',
    projectId: 'my-coach-flutter',
    storageBucket: 'my-coach-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrme3XbDqNzUh_UMtevnsUSsfrtkEygM',
    appId: '1:726428908817:ios:41e169f903aea6f855a0b0',
    messagingSenderId: '726428908817',
    projectId: 'my-coach-flutter',
    storageBucket: 'my-coach-flutter.firebasestorage.app',
    iosBundleId: 'com.example.myCoachServerpodChallengeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.example.myCoachServerpodChallengeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}