/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_client/serverpod_client.dart' as _i1;
import 'dart:async' as _i2;
import 'package:my_coach_serverpod_challenge_client/src/protocol/coach_message.dart'
    as _i3;
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _i4;
import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _i5;
import 'package:my_coach_serverpod_challenge_client/src/protocol/coach.dart'
    as _i6;
import 'package:my_coach_serverpod_challenge_client/src/protocol/user_device.dart'
    as _i7;
import 'package:my_coach_serverpod_challenge_client/src/protocol/greetings/greeting.dart'
    as _i8;
import 'package:my_coach_serverpod_challenge_client/src/protocol/task_reminder.dart'
    as _i9;
import 'package:my_coach_serverpod_challenge_client/src/protocol/subtask.dart'
    as _i10;
import 'package:my_coach_serverpod_challenge_client/src/protocol/task.dart'
    as _i11;
import 'package:my_coach_serverpod_challenge_client/src/protocol/voice_task_draft.dart'
    as _i12;
import 'protocol.dart' as _i13;

/// Endpoint for streaming audio files for coach messages.
/// {@category Endpoint}
class EndpointAudio extends _i1.EndpointRef {
  EndpointAudio(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'audio';

  /// Gets the audio data for a coach message.
  /// Returns the audio as a base64-encoded string (Serverpod can't serialize
  /// Uint8List).
  /// Only the owner of the associated task can access the audio.
  _i2.Future<String?> getAudio(int messageId) =>
      caller.callServerEndpoint<String?>(
        'audio',
        'getAudio',
        {'messageId': messageId},
      );

  /// Gets the coach message details including text content.
  /// Only the owner of the associated task can access the message.
  _i2.Future<_i3.CoachMessage?> getMessage(int messageId) =>
      caller.callServerEndpoint<_i3.CoachMessage?>(
        'audio',
        'getMessage',
        {'messageId': messageId},
      );

  /// Gets all messages for a specific task.
  /// Only the owner of the task can access its messages.
  _i2.Future<List<_i3.CoachMessage>> getMessagesForTask(int taskId) =>
      caller.callServerEndpoint<List<_i3.CoachMessage>>(
        'audio',
        'getMessagesForTask',
        {'taskId': taskId},
      );
}

/// {@category Endpoint}
class EndpointGoogleIdp extends _i4.EndpointGoogleIdpBase {
  EndpointGoogleIdp(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'googleIdp';

  /// Validates a Google ID token and either logs in the associated user or
  /// creates a new user account if the Google account ID is not yet known.
  ///
  /// If a new user is created an associated [UserProfile] is also created.
  @override
  _i2.Future<_i5.AuthSuccess> login({
    required String idToken,
    required String? accessToken,
  }) => caller.callServerEndpoint<_i5.AuthSuccess>(
    'googleIdp',
    'login',
    {
      'idToken': idToken,
      'accessToken': accessToken,
    },
  );
}

/// By extending [RefreshJwtTokensEndpoint], the JWT token refresh endpoint
/// is made available on the server and enables automatic token refresh on the client.
/// {@category Endpoint}
class EndpointJwtRefresh extends _i5.EndpointRefreshJwtTokens {
  EndpointJwtRefresh(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'jwtRefresh';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _i2.Future<_i5.AuthSuccess> refreshAccessToken({
    required String refreshToken,
  }) => caller.callServerEndpoint<_i5.AuthSuccess>(
    'jwtRefresh',
    'refreshAccessToken',
    {'refreshToken': refreshToken},
    authenticated: false,
  );
}

/// Endpoint for retrieving coach characters.
/// {@category Endpoint}
class EndpointCoach extends _i1.EndpointRef {
  EndpointCoach(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'coach';

  /// Gets all available coach characters.
  _i2.Future<List<_i6.Coach>> getCoaches() =>
      caller.callServerEndpoint<List<_i6.Coach>>(
        'coach',
        'getCoaches',
        {},
      );

  /// Gets a specific coach by ID.
  _i2.Future<_i6.Coach?> getCoach(int id) =>
      caller.callServerEndpoint<_i6.Coach?>(
        'coach',
        'getCoach',
        {'id': id},
      );
}

/// Endpoint for managing FCM device registrations.
/// {@category Endpoint}
class EndpointDevice extends _i1.EndpointRef {
  EndpointDevice(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'device';

  /// Registers or updates an FCM token for the authenticated user's device.
  _i2.Future<_i7.UserDevice> registerDevice(
    String fcmToken,
    String platform,
  ) => caller.callServerEndpoint<_i7.UserDevice>(
    'device',
    'registerDevice',
    {
      'fcmToken': fcmToken,
      'platform': platform,
    },
  );

  /// Removes the device registration for the authenticated user.
  /// Returns the number of deleted devices.
  _i2.Future<int> unregisterDevice() => caller.callServerEndpoint<int>(
    'device',
    'unregisterDevice',
    {},
  );
}

/// This is an example endpoint that returns a greeting message through
/// its [hello] method.
/// {@category Endpoint}
class EndpointGreeting extends _i1.EndpointRef {
  EndpointGreeting(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'greeting';

  /// Returns a personalized greeting message: "Hello {name}".
  _i2.Future<_i8.Greeting> hello(String name) =>
      caller.callServerEndpoint<_i8.Greeting>(
        'greeting',
        'hello',
        {'name': name},
      );
}

/// Endpoint for managing task reminders.
/// {@category Endpoint}
class EndpointTaskReminder extends _i1.EndpointRef {
  EndpointTaskReminder(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'taskReminder';

  /// Gets all reminders for a task.
  ///
  /// [taskId] - The ID of the task
  ///
  /// Returns a list of reminders ordered by minutesBefore.
  _i2.Future<List<_i9.TaskReminder>> getReminders(int taskId) =>
      caller.callServerEndpoint<List<_i9.TaskReminder>>(
        'taskReminder',
        'getReminders',
        {'taskId': taskId},
      );

  /// Adds a new reminder to a task.
  ///
  /// [taskId] - The ID of the task
  /// [minutesBefore] - Minutes before due time (0 = at due time)
  ///
  /// Returns the created reminder.
  _i2.Future<_i9.TaskReminder> addReminder(
    int taskId,
    int minutesBefore,
  ) => caller.callServerEndpoint<_i9.TaskReminder>(
    'taskReminder',
    'addReminder',
    {
      'taskId': taskId,
      'minutesBefore': minutesBefore,
    },
  );

  /// Removes a reminder.
  ///
  /// [reminderId] - The ID of the reminder to remove
  _i2.Future<void> removeReminder(int reminderId) =>
      caller.callServerEndpoint<void>(
        'taskReminder',
        'removeReminder',
        {'reminderId': reminderId},
      );

  /// Updates a reminder's time.
  ///
  /// [reminderId] - The ID of the reminder to update
  /// [minutesBefore] - New minutes before due time
  ///
  /// Returns the updated reminder.
  _i2.Future<_i9.TaskReminder> updateReminder(
    int reminderId,
    int minutesBefore,
  ) => caller.callServerEndpoint<_i9.TaskReminder>(
    'taskReminder',
    'updateReminder',
    {
      'reminderId': reminderId,
      'minutesBefore': minutesBefore,
    },
  );

  /// Adds default reminders to a task (at due time only).
  ///
  /// [taskId] - The ID of the task
  ///
  /// Returns the list of created reminders.
  _i2.Future<List<_i9.TaskReminder>> addDefaultReminders(int taskId) =>
      caller.callServerEndpoint<List<_i9.TaskReminder>>(
        'taskReminder',
        'addDefaultReminders',
        {'taskId': taskId},
      );

  /// Removes all reminders from a task.
  ///
  /// [taskId] - The ID of the task
  ///
  /// Returns the number of removed reminders.
  _i2.Future<int> removeAllReminders(int taskId) =>
      caller.callServerEndpoint<int>(
        'taskReminder',
        'removeAllReminders',
        {'taskId': taskId},
      );
}

/// Endpoint for managing subtasks.
/// {@category Endpoint}
class EndpointSubtask extends _i1.EndpointRef {
  EndpointSubtask(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'subtask';

  /// Gets all subtasks for a task.
  ///
  /// [taskId] - The ID of the parent task
  ///
  /// Returns a list of subtasks ordered by orderIndex.
  _i2.Future<List<_i10.Subtask>> getSubtasks(int taskId) =>
      caller.callServerEndpoint<List<_i10.Subtask>>(
        'subtask',
        'getSubtasks',
        {'taskId': taskId},
      );

  /// Marks a subtask as completed.
  ///
  /// [subtaskId] - The ID of the subtask to complete
  ///
  /// Returns the updated subtask.
  _i2.Future<_i10.Subtask> completeSubtask(int subtaskId) =>
      caller.callServerEndpoint<_i10.Subtask>(
        'subtask',
        'completeSubtask',
        {'subtaskId': subtaskId},
      );

  /// Marks a subtask as incomplete.
  ///
  /// [subtaskId] - The ID of the subtask to uncomplete
  ///
  /// Returns the updated subtask.
  _i2.Future<_i10.Subtask> uncompleteSubtask(int subtaskId) =>
      caller.callServerEndpoint<_i10.Subtask>(
        'subtask',
        'uncompleteSubtask',
        {'subtaskId': subtaskId},
      );

  /// Adds a new subtask to a task.
  ///
  /// [taskId] - The ID of the parent task
  /// [name] - The name/description of the subtask
  ///
  /// Returns the created subtask.
  _i2.Future<_i10.Subtask> addSubtask(
    int taskId,
    String name,
  ) => caller.callServerEndpoint<_i10.Subtask>(
    'subtask',
    'addSubtask',
    {
      'taskId': taskId,
      'name': name,
    },
  );

  /// Updates a subtask's name.
  ///
  /// [subtaskId] - The ID of the subtask to update
  /// [name] - The new name for the subtask
  ///
  /// Returns the updated subtask.
  _i2.Future<_i10.Subtask> updateSubtask(
    int subtaskId,
    String name,
  ) => caller.callServerEndpoint<_i10.Subtask>(
    'subtask',
    'updateSubtask',
    {
      'subtaskId': subtaskId,
      'name': name,
    },
  );

  /// Deletes a subtask.
  ///
  /// [subtaskId] - The ID of the subtask to delete
  _i2.Future<void> deleteSubtask(int subtaskId) =>
      caller.callServerEndpoint<void>(
        'subtask',
        'deleteSubtask',
        {'subtaskId': subtaskId},
      );

  /// Reorders subtasks within a task.
  ///
  /// [subtaskIds] - List of subtask IDs in the desired order
  _i2.Future<void> reorderSubtasks(List<int> subtaskIds) =>
      caller.callServerEndpoint<void>(
        'subtask',
        'reorderSubtasks',
        {'subtaskIds': subtaskIds},
      );
}

/// Endpoint for managing user tasks with CRUD operations.
/// {@category Endpoint}
class EndpointTask extends _i1.EndpointRef {
  EndpointTask(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'task';

  /// Creates a new task for the authenticated user.
  /// If dueTime is set, default reminders (30 min before + at due time) are created.
  _i2.Future<_i11.Task> createTask(_i11.Task task) =>
      caller.callServerEndpoint<_i11.Task>(
        'task',
        'createTask',
        {'task': task},
      );

  /// Creates a new task with custom reminder settings.
  ///
  /// [task] - The task to create
  /// [reminderMinutes] - List of minutesBefore values for reminders
  ///   - Empty list = no reminders
  ///   - null = use defaults (30 min before + at due time)
  ///
  /// Returns the created task.
  _i2.Future<_i11.Task> createTaskWithReminders(
    _i11.Task task,
    List<int>? reminderMinutes,
  ) => caller.callServerEndpoint<_i11.Task>(
    'task',
    'createTaskWithReminders',
    {
      'task': task,
      'reminderMinutes': reminderMinutes,
    },
  );

  /// Updates an existing task owned by the authenticated user.
  _i2.Future<_i11.Task> updateTask(_i11.Task task) =>
      caller.callServerEndpoint<_i11.Task>(
        'task',
        'updateTask',
        {'task': task},
      );

  /// Deletes a task owned by the authenticated user.
  /// Also deletes associated coach messages, reminders, and subtasks.
  /// Returns the number of deleted tasks.
  _i2.Future<int> deleteTask(int taskId) => caller.callServerEndpoint<int>(
    'task',
    'deleteTask',
    {'taskId': taskId},
  );

  /// Marks a task as completed.
  /// Also marks all pending reminders as sent.
  _i2.Future<_i11.Task> completeTask(int taskId) =>
      caller.callServerEndpoint<_i11.Task>(
        'task',
        'completeTask',
        {'taskId': taskId},
      );

  /// Gets all tasks for the authenticated user.
  _i2.Future<List<_i11.Task>> getUserTasks() =>
      caller.callServerEndpoint<List<_i11.Task>>(
        'task',
        'getUserTasks',
        {},
      );

  /// Gets all incomplete tasks for the authenticated user.
  _i2.Future<List<_i11.Task>> getPendingTasks() =>
      caller.callServerEndpoint<List<_i11.Task>>(
        'task',
        'getPendingTasks',
        {},
      );

  /// Marks a completed task as incomplete (uncomplete).
  /// Resets reminders if task has a due time in the future.
  _i2.Future<_i11.Task> uncompleteTask(int taskId) =>
      caller.callServerEndpoint<_i11.Task>(
        'task',
        'uncompleteTask',
        {'taskId': taskId},
      );
}

/// Endpoint for handling voice input and AI task parsing.
/// {@category Endpoint}
class EndpointVoiceInput extends _i1.EndpointRef {
  EndpointVoiceInput(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'voiceInput';

  /// Parses voice input using AI and creates/updates a draft task.
  ///
  /// [transcribedText] - The speech-to-text result
  /// [sessionId] - Optional session ID for multi-turn clarification
  ///
  /// Returns the created or updated VoiceTaskDraft.
  _i2.Future<_i12.VoiceTaskDraft> parseVoiceInput(
    String transcribedText, {
    String? sessionId,
  }) => caller.callServerEndpoint<_i12.VoiceTaskDraft>(
    'voiceInput',
    'parseVoiceInput',
    {
      'transcribedText': transcribedText,
      'sessionId': sessionId,
    },
  );

  /// Confirms a draft and creates the actual task with reminders and subtasks.
  ///
  /// [draftId] - The ID of the draft to confirm
  /// [overrideCoachId] - Optional coach ID to override AI suggestion
  /// [overrideReminders] - Optional reminders to override AI suggestion (JSON array)
  ///
  /// Returns the created Task.
  _i2.Future<_i11.Task> confirmDraft(
    int draftId, {
    int? overrideCoachId,
    String? overrideReminders,
  }) => caller.callServerEndpoint<_i11.Task>(
    'voiceInput',
    'confirmDraft',
    {
      'draftId': draftId,
      'overrideCoachId': overrideCoachId,
      'overrideReminders': overrideReminders,
    },
  );

  /// Discards a draft.
  ///
  /// [draftId] - The ID of the draft to discard
  _i2.Future<void> discardDraft(int draftId) => caller.callServerEndpoint<void>(
    'voiceInput',
    'discardDraft',
    {'draftId': draftId},
  );

  /// Gets all pending drafts for the authenticated user.
  _i2.Future<List<_i12.VoiceTaskDraft>> getPendingDrafts() =>
      caller.callServerEndpoint<List<_i12.VoiceTaskDraft>>(
        'voiceInput',
        'getPendingDrafts',
        {},
      );
}

class Modules {
  Modules(Client client) {
    serverpod_auth_idp = _i4.Caller(client);
    serverpod_auth_core = _i5.Caller(client);
  }

  late final _i4.Caller serverpod_auth_idp;

  late final _i5.Caller serverpod_auth_core;
}

class Client extends _i1.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    @Deprecated(
      'Use authKeyProvider instead. This will be removed in future releases.',
    )
    super.authenticationKeyManager,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _i1.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_i1.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
  }) : super(
         host,
         _i13.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
       ) {
    audio = EndpointAudio(this);
    googleIdp = EndpointGoogleIdp(this);
    jwtRefresh = EndpointJwtRefresh(this);
    coach = EndpointCoach(this);
    device = EndpointDevice(this);
    greeting = EndpointGreeting(this);
    taskReminder = EndpointTaskReminder(this);
    subtask = EndpointSubtask(this);
    task = EndpointTask(this);
    voiceInput = EndpointVoiceInput(this);
    modules = Modules(this);
  }

  late final EndpointAudio audio;

  late final EndpointGoogleIdp googleIdp;

  late final EndpointJwtRefresh jwtRefresh;

  late final EndpointCoach coach;

  late final EndpointDevice device;

  late final EndpointGreeting greeting;

  late final EndpointTaskReminder taskReminder;

  late final EndpointSubtask subtask;

  late final EndpointTask task;

  late final EndpointVoiceInput voiceInput;

  late final Modules modules;

  @override
  Map<String, _i1.EndpointRef> get endpointRefLookup => {
    'audio': audio,
    'googleIdp': googleIdp,
    'jwtRefresh': jwtRefresh,
    'coach': coach,
    'device': device,
    'greeting': greeting,
    'taskReminder': taskReminder,
    'subtask': subtask,
    'task': task,
    'voiceInput': voiceInput,
  };

  @override
  Map<String, _i1.ModuleEndpointCaller> get moduleLookup => {
    'serverpod_auth_idp': modules.serverpod_auth_idp,
    'serverpod_auth_core': modules.serverpod_auth_core,
  };
}
